### PR TITLE
ci/ui: add label size regression test (#706)

### LINKED ISSUE #706: e2e ui: Regression test for labels max size in UI
Add regression to make sure we cannot use a label greather than 63 characters, otherwise elemental node will fail to boot.
More details here https://github.com/rancher/elemental-ui/issues/77

### PR DESCRIPTION
**Pull request by juadk**
Fix #706 

The PR tests if we get a warning banner and if the Create button is disabled when we exceed the label max size.
image
image

## Verification run

Local:
Screenshot 2023-06-07 at 15 00 23

[UI-K3s-Rancher_Stable](https://github.com/rancher/elemental/actions/runs/5200304558) ✔️ 
Screenshot 2023-06-07 at 15 26 45

### CODE REVIEW

File: tests/cypress/latest/support/functions.ts [hunk 1]
```diff
@@ -529,3 +529,21 @@ Cypress.Commands.add('checkFilter', ({
...
+
+Cypress.Commands.add('checkLabelSize', ({
+  sizeToCheck}) => {
+    cy.clickNavMenu(["Dashboard"]);
+    cy.getBySel('button-create-registration-endpoint')
+      .click();
+    if (sizeToCheck == "name") {
+      cy.addMachInvLabel({labelName: 'labeltoolonggggggggggggggggggggggggggggggggggggggggggggggggggggg', labelValue: 'mylabelvalue', useHardwareLabels: false});
+    } else if (sizeToCheck == "value") {
+      cy.addMachInvLabel({labelName: 'mylabelname', labelValue: 'valuetoolonggggggggggggggggggggggggggggggggggggggggggggggggggggg', useHardwareLabels: false});
```
Comment (ldevulder) [inline tests/cypress/latest/support/functions.ts:541]: Maybe a variable could have been useful for this "too long" value ;-) but that's fine.

**Review by ldevulder — APPROVED** [review]
